services:
  trapa-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
      - GOOGLE_CLOUD_PROJECT=trapa-dev
      - GOOGLE_CLOUD_PROJECT_NUMBER=584032921839
    volumes:
      - "/mnt/c/Users/t/AppData/Roaming/gcloud/application_default_credentials.json:/gcp/creds.json:ro"
