name: Development Deployment

on:
  push:
    branches: 
      - master

env:
  PROJECT_ID: trapa-dev 
  REPO_LOCATION: australia-southeast1 
  REPO_NAME: trapa-api
  IMAGE_NAME: trapa-api
  SERVICE_LOCATION: australia-southeast1 
  SERVICE_NAME: trapa-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.REPO_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          version=${{ steps.version.outputs.version }}+${{ steps.version.outputs.increment }}
          docker build -t "${{ env.REPO_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$version" --build-arg="COMMIT=${{ github.sha }}" --build-arg="VERSION=$version" ./
          docker push "${{ env.REPO_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$version"


      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.SERVICE_LOCATION }}
          image: ${{ env.REPO_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}+${{ steps.version.outputs.increment }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}